# -*- coding: utf-8 -*-
"""ML_day_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IwLoJeLWPdliqPeu2OeA_n1BqzC3vtCN
"""

#importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree
import pickle

#reading the dataset and preprocessing
dataset = pd.read_csv('http://iali.in/datasets/Social_Network_Ads.csv')

x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

#sample randomly
dataset.sample()

#generate descriptive statistics
dataset.describe()

# Splitting dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

#fitting the decision tree to training set
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

# Saving model to disk
pickle.dump(clf, open('model.pkl','wb'))